#Nombre del workflow
name: Build and test of Java Project

#Evento que desencadenará el workflow
on: [push]

#Configuración por defecto.
defaults:
 run:
  #Se indica el directorio desde donde se ejecutarán los jobs.
  working-directory: example1-gitactions

#lista de trabajos a realizar
jobs:
 #Job a ejecutar
 build:
   #Máquina en la que se va a ejecutar el job 
   runs-on: ubuntu-latest
 
   #Lista de steps/tareas a realizar dentro del job
   steps:
     #Tarea que hace un checkout del repositorio
     - uses: actions/checkout@v2
     #Tarea que instala en la máquina java 11
     - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
     #tarea que ejecuta un mvn package
     - name: Build with Maven
       run: mvn -B package --file pom.xml

