name: Get version from pom.xml
 
on: [push]

defaults:
 run:
  working-directory: example1-gitactions

jobs:
 get-version:
   runs-on: ubuntu-latest
 
   steps:

     - uses: actions/checkout@v2

     - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
         
	 - name: Set Release version env variable
	   run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

     - name: test echo
       run: echo "Get Version : ${{ env.RELEASE_VERSION }}"