name: Get version from pom.xml
 
on: [push]

defaults:
 run:
  working-directory: example1-gitactions

jobs:
 get-version:
   runs-on: ubuntu-latest
 
   steps:

     - uses: actions/checkout@v2

     - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
         
     - name: Extract Maven project version
       run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
       id: project

     - name: Show extracted  Maven project version
       run: echo "Version is ${{ steps.project.outputs.version }}"
       
 use-version:
    runs-on: ubuntu-latest
 
   steps:
      - name: Show extracted  Maven project version
       run: echo "Version is ${{ steps.project.outputs.version }}"