#Nombre del workflow
name: Get version from pom.xml - env
 #Evento que desencadenará el workflow
on: [push]
#Configuración por defecto.
defaults:
 run:
  #Se indica el directorio desde donde se ejecutarán los jobs.
  working-directory: example1-gitactions

#lista de variables de entorno inicializadas para usar en los jobs
env: 
  GITHUB_RELEASE_VERSION: "prueba"
  
#lista de trabajos a realizar
jobs:
 #Job a ejecutar 
 get-version-env:
     #Máquina en la que se va a ejecutar el job 
    runs-on: ubuntu-latest
    #Lista de steps/tareas a realizar dentro del job 
    steps:
      #Tarea que hace un checkout del repositorio
      - uses: actions/checkout@v2
      #Tarea que instala en la máquina java 11
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      #Tarea extrae a la variable de entorno GITHUB_RELEASE_VERSION, la version existente en el pom.xml
      - name: Extract Maven project version
        run: echo "GITHUB_RELEASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
      #Tarea que hace un echo de la variable de entorno GITHUB_RELEASE_VERSION. Mostrará el valor de la version del pom
      - name: Show extracted  Maven project version
        run: echo "Version is ${{ env.GITHUB_RELEASE_VERSION }}"
 #Job a ejecutar 
 use-version:
    #Se indica que este job va a depender del anterior. Es decir, se va a ejecutar el otro primero.
    needs: get-version-env
    #Máquina en la que se va a ejecutar el job 
    runs-on: ubuntu-latest
    #Lista de steps/tareas a realizar dentro del job 
    steps:
      #Tarea que hace un checkout del repositorio
      - uses: actions/checkout@v2
      #Tarea que instala en la máquina java 11
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      #Tarea que hace un echo de la variable de entorno GITHUB_RELEASE_VERSION. Mostrará el valor por defecto "prueba"
      - name: Show extracted  Maven project version
        run: echo "Version is ${{ env.GITHUB_RELEASE_VERSION }}"