name: Build and test of Java Project
 
on: [push]
 
jobs:
 build:
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
     - name: cd in example 1
        run: cd example1-gitactions
     - name: Build with Maven
       run: mvn -B package --file pom.xml