name: Build and test of Java Project
 
on: [push]

defaults:
 run:
  working-directory: example1-gitactions

jobs:
 build:
   runs-on: ubuntu-latest
 
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
     - name: test echo
       run: echo "Testing echo"